In [1]:
def my_function():
    "This prints a string"
    print("Hello from a function")

In [2]:
my_function()

Hello from a function


In [3]:
def printme(nama): # parameter
    "This prints a nama string into this function"
    print(nama)

In [4]:
printme("Adi") # argument

Adi


In [5]:
printme("nama saya adalah...")

nama saya adalah...


In [6]:
def printme(nama, alamat): 
    "This prints a nama string into this function"
    print(nama)
    print(alamat)

In [7]:
printme("Adi", "Yogyakarta")

Adi
Yogyakarta


In [9]:
printme(alamat="Yogyakarta",nama="Adi")

Adi
Yogyakarta


In [10]:
def printme(nama ="Adi", alamat ="Yogyakarta"): 
    "This prints a nama string into this function"
    print(nama)
    print(alamat)
    return

In [11]:
printme()

Adi
Yogyakarta


In [12]:
printme("Hacktiv8")

Hacktiv8
Yogyakarta


In [14]:
printme(alamat="Medan")

Adi
Medan


In [15]:
printme("Hacktive8", "Medan")

Hacktive8
Medan


In [27]:
def printinfo(arg1, *arg2):
    "This print a variable passed arguments"
    print("Output is: ")
    print(arg1)
    for var in arg2:
        print(var)
    return;

In [28]:
printinfo(30)

Output is: 
30


In [29]:
printinfo(1,2,3,4,5,6,7,8,9)

Output is: 
1
2
3
4
5
6
7
8
9


In [30]:
sum = lambda arg1, arg2: arg1 + arg2;

In [31]:
sum(10, 20)

30

In [32]:
print("Value of total:", sum(20,20))

Value of total: 40


In [35]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total

In [36]:
sum(10, 20)

30

In [40]:
print("Value of total:", sum(20, 20))

Value of total: 40


In [41]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total, total1

In [42]:
sum(10, 20)

(30, 80)

In [55]:
kucing = 20

def jumlahHewan():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahHewan() :
    anjing = 20
    tambahan = anjing + kucing
    return tambahan

In [56]:
jumlahHewan()

50

In [57]:
tambahHewan()

40

In [58]:
import sys

In [59]:
sys.path

['C:\\Users\\Adi Nugroho',
 'C:\\ProgramData\\Anaconda3\\python37.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 '',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Adi Nugroho\\.ipython']

In [60]:
sys.path.append(r'/user/Adi Nugroho/Desktop/H8package/')

In [61]:
sys.path

['C:\\Users\\Adi Nugroho',
 'C:\\ProgramData\\Anaconda3\\python37.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 '',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Adi Nugroho\\.ipython',
 '/user/Adi Nugroho/Desktop/H8package/']

In [62]:
import mod

ModuleNotFoundError: No module named 'mod'

In [63]:
import mod

ModuleNotFoundError: No module named 'mod'

In [67]:
import mod

ModuleNotFoundError: No module named 'mod'

In [65]:
import mod

ModuleNotFoundError: No module named 'mod'

In [68]:
s

NameError: name 's' is not defined

In [69]:
import mod

ModuleNotFoundError: No module named 'mod'

In [70]:
my_module.s

NameError: name 'my_module' is not defined

In [71]:
import mod

ModuleNotFoundError: No module named 'mod'

In [72]:
s

NameError: name 's' is not defined

In [73]:
sys.path

['C:\\Users\\Adi Nugroho',
 'C:\\ProgramData\\Anaconda3\\python37.zip',
 'C:\\ProgramData\\Anaconda3\\DLLs',
 'C:\\ProgramData\\Anaconda3\\lib',
 'C:\\ProgramData\\Anaconda3',
 '',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Adi Nugroho\\.ipython',
 '/user/Adi Nugroho/Desktop/H8package/']

In [74]:
import mod

ModuleNotFoundError: No module named 'mod'

In [75]:
!pip --version

pip 20.0.2 from C:\ProgramData\Anaconda3\lib\site-packages\pip (python 3.7)



In [76]:
!pip install requests

In [77]:
import requests

In [78]:
## Numpy

In [79]:
import numpy as np

In [80]:
## Creating Array

a = np.array([1,2,3])

In [81]:
a

array([1, 2, 3])

In [82]:
b = [1,2,3]

In [83]:
b

[1, 2, 3]

In [84]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
c = np.zeros(5)

In [86]:
print(c)

[0. 0. 0. 0. 0.]


In [87]:
d = np.ones(5)

In [88]:
print(d)

[1. 1. 1. 1. 1.]


In [89]:
np.arange(4)

array([0, 1, 2, 3])

In [90]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [92]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [93]:
print(arr)

[1 2 3 4 5 6 7 8]


In [94]:
np.append(arr, [1,2]) # add (nambah)

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [95]:
np.delete(arr,1) # delete

array([1, 3, 4, 5, 6, 7, 8])

In [96]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [97]:
print(arr)

[2 1 5 3 7 4 6 8]


In [100]:
np.sort(arr) # sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

In [101]:
## shape dan size

In [102]:
array_example = np.array([[0,1,2,3],
                          [4,5,6,7]])


In [103]:
print(array_example)

[[0 1 2 3]
 [4 5 6 7]]


In [104]:
array_example.ndim

2

In [105]:
array_example.size

8

In [107]:
array_example.shape

(2, 4)

In [111]:
array_example = np.array([[0,1,2,3],
                          [4,5,6,7],
                         [8,9,10,11],
                         [12,13,14,15]])

In [112]:
print(array_example)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [113]:
# reshape

In [115]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [116]:
b = a.reshape(3, 2)

In [117]:
print (b)

[[0 1]
 [2 3]
 [4 5]]


In [118]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [119]:
# convert 1D to 2D

In [120]:
a

array([0, 1, 2, 3, 4, 5])

In [121]:
a. shape

(6,)

In [122]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [123]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [124]:
row_vector = a[np.newaxis, :]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [125]:
print(a.shape)

(6,)


In [126]:
np.expand_dims(a, axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [132]:
e = np.expand_dims(a,axis=0)
prin(e)
print (e.shape)

NameError: name 'prin' is not defined

In [133]:
## indexing and slicing

In [134]:
data = np.array([1,2,3])

In [135]:
data[0]

1

In [136]:
data[1]

2

In [137]:
data[0:2]

array([1, 2])

In [138]:
data[1:]

array([2, 3])

In [139]:
data[-2]

2

In [140]:
a = np.array([[1,2,3,4,],[5,6,7,8],[9,10,11,12]])

In [141]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [142]:
a[a<5]

array([1, 2, 3, 4])

In [143]:
# view dan copy

In [144]:
b = a.view()

In [145]:
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [146]:
c = a.copy()

In [147]:
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [148]:
# basic array operations

In [149]:
a_1

NameError: name 'a_1' is not defined

In [150]:
a_2

NameError: name 'a_2' is not defined

In [151]:
a.min()

1

In [152]:
a.max()

12

In [153]:
a.min(axis=0)

array([1, 2, 3, 4])

In [154]:
a.min(axis=1)

array([1, 5, 9])

In [155]:
a.max(axis=0)

array([ 9, 10, 11, 12])

In [156]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [157]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [158]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [160]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [161]:
np.random.random((3,2))

array([[0.45423456, 0.14253489],
       [0.48936083, 0.86409173],
       [0.53697679, 0.79447232]])

In [162]:
# Matrix Arithmatic

In [165]:
data = np.array([[1,2], [3,4]])

In [166]:
print(data)

[[1 2]
 [3 4]]


In [167]:
ones = np.ones([2,2])

In [168]:
print(ones)

[[1. 1.]
 [1. 1.]]


In [169]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [170]:
ones_row = np.ones((1,2))

In [171]:
print(ones_row)

[[1. 1.]]


In [172]:
data + ones_row

array([[2., 3.],
       [4., 5.]])

In [173]:
a_1 = np.array([[1,2,3,], [4,5,6]])
print(a_1)

[[1 2 3]
 [4 5 6]]


In [175]:
a_1 = np.array([[1,2,3,], [4,5,6]])
print(a_1)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [177]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [178]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [179]:
data = np.array([[1,2], [3,4], [5,6]])

In [180]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [181]:
data[0,1]

2

In [182]:
data[1,1]

4

In [183]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [187]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [188]:
data[0:2, 0]

array([1, 3])

In [189]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [190]:
data.max()

6

In [191]:
data.min()

1

In [192]:
data.sum()

21

In [193]:
data.max(axis=1)

array([2, 4, 6])

In [194]:
data.max(axis=0)

array([5, 6])

In [195]:
# transposing adn reshaping

In [196]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [197]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [198]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [200]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [202]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [205]:
arr = np.arange(6).reshape((2,3))

In [206]:
print(arr)

[[0 1 2]
 [3 4 5]]


In [207]:
# ND Array

In [212]:
ndarr = np.array([[[1,2], [3,4]],
                [[5,6], [7,8]]])

In [213]:
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [214]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [215]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [216]:
np.random.random((4,3,2))

array([[[0.53019678, 0.59361399],
        [0.53599962, 0.69405262],
        [0.95527142, 0.74940797]],

       [[0.77919852, 0.65906365],
        [0.7696659 , 0.68236419],
        [0.72248239, 0.29467602]],

       [[0.39519333, 0.25939959],
        [0.40988765, 0.0727022 ],
        [0.96239447, 0.12063106]],

       [[0.62097871, 0.21319489],
        [0.35666054, 0.07403117],
        [0.43658911, 0.53282634]]])

In [217]:
# flaten

In [219]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [220]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [221]:
a = np.random.random(5)

In [222]:
print (a)

[0.58646323 0.53682518 0.80420517 0.37519896 0.80452937]


In [223]:
a.shape # rank 1 array

(5,)

In [224]:
(5,)

(5,)

In [225]:
a.T

array([0.58646323, 0.53682518, 0.80420517, 0.37519896, 0.80452937])

In [226]:
np.dot(a,a.T)

2.0669081091269006

In [227]:
a = np.random.rand(5,1) # colom vector

In [228]:
print(a)

[[0.61209597]
 [0.03974319]
 [0.96034129]
 [0.1932447 ]
 [0.95267134]]


In [229]:
a.shape

(5, 1)

In [230]:
a.T

array([[0.61209597, 0.03974319, 0.96034129, 0.1932447 , 0.95267134]])

In [231]:
np.dot(a,a.T)

array([[0.37466147, 0.02432664, 0.58782103, 0.1182843 , 0.58312628],
       [0.02432664, 0.00157952, 0.03816702, 0.00768016, 0.03786219],
       [0.58782103, 0.03816702, 0.9222554 , 0.18558087, 0.91488963],
       [0.1182843 , 0.00768016, 0.18558087, 0.03734351, 0.18409869],
       [0.58312628, 0.03786219, 0.91488963, 0.18409869, 0.90758269]])

In [234]:
a = np.random.rand(5,1)

In [235]:
print(a)

[[0.68440513]
 [0.09346224]
 [0.89996523]
 [0.15928876]
 [0.9018741 ]]


In [236]:
a.shape

(5, 1)

In [237]:
a.T

array([[0.68440513, 0.09346224, 0.89996523, 0.15928876, 0.9018741 ]])

In [239]:
np.dot(a,a.T)

array([[0.46841038, 0.06396604, 0.61594082, 0.10901804, 0.61724726],
       [0.06396604, 0.00873519, 0.08411277, 0.01488748, 0.08429118],
       [0.61594082, 0.08411277, 0.80993741, 0.14335434, 0.81165533],
       [0.10901804, 0.01488748, 0.14335434, 0.02537291, 0.1436584 ],
       [0.61724726, 0.08429118, 0.81165533, 0.1436584 , 0.81337689]])

In [240]:
a = np.random.rand(1,5)

In [241]:
a.shape

(1, 5)

In [242]:
a

array([[0.85603894, 0.11016304, 0.20789004, 0.07700402, 0.20846703]])

In [244]:
ndarr = np.array([[[1,2], [3,4]],[[5,6], [7,8]]])

In [246]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])